In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('hr_analytics_messy_dataset.csv')
df

,Employee_ID,Age,Department,JobRole,Monthly_Income,Years_At_Company,Gender,Attrition,Age_Group,Experience_Level,Attrition_Flag,Salary_Category
0,1,56,Finance,Manager,92214,14,Male,Yes,46-60,Senior,1,High
1,2,46,HR,Analyst,47052,10,Male,No,46-60,Mid,0,Medium
2,3,32,Marketing,Executive,67769,0,Female,No,26-35,New,0,High
3,4,25,Sales,Analyst,56032,17,Female,Yes,18-25,Senior,1,Medium
4,5,38,HR,Clerk,98721,11,Female,No,36-45,Senior,0,High
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,43,Sales,Engineer,73767,18,Female,No,36-45,Senior,0,High
1996,1997,42,Finance,Executive,36469,4,Male,No,36-45,Junior,0,Medium
1997,1998,47,Finance,Engineer,11313,6,Female,No,46-60,Mid,0,Low
1998,1999,28,Marketing,Manager,17847,13,Female,No,26-35,Senior,0,Low
1999,2000,24,IT,Engineer,60222,2,Male,No,18-25,New,0,High

In [7]:
df.head()

,Employee_ID,Age,Department,JobRole,Monthly_Income,Years_At_Company,Gender,Attrition,Age_Group,Experience_Level,Attrition_Flag,Salary_Category
0,1,56,Finance,Manager,92214,14,Male,Yes,46-60,Senior,1,High
1,2,46,HR,Analyst,47052,10,Male,No,46-60,Mid,0,Medium
2,3,32,Marketing,Executive,67769,0,Female,No,26-35,New,0,High
3,4,25,Sales,Analyst,56032,17,Female,Yes,18-25,Senior,1,Medium
4,5,38,HR,Clerk,98721,11,Female,No,36-45,Senior,0,High

In [8]:
df.tail()

,Employee_ID,Age,Department,JobRole,Monthly_Income,Years_At_Company,Gender,Attrition,Age_Group,Experience_Level,Attrition_Flag,Salary_Category
1995,1996,43,Sales,Engineer,73767,18,Female,No,36-45,Senior,0,High
1996,1997,42,Finance,Executive,36469,4,Male,No,36-45,Junior,0,Medium
1997,1998,47,Finance,Engineer,11313,6,Female,No,46-60,Mid,0,Low
1998,1999,28,Marketing,Manager,17847,13,Female,No,26-35,Senior,0,Low
1999,2000,24,IT,Engineer,60222,2,Male,No,18-25,New,0,High

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       2000 non-null   int64
 1   Age               2000 non-null   int64
 2   Department        2000 non-null   object
 3   JobRole           2000 non-null   object
 4   Monthly_Income    2000 non-null   int64
 5   Years_At_Company  2000 non-null   int64
 6   Gender            2000 non-null   object
 7   Attrition         2000 non-null   object
 8   Age_Group         1954 non-null   object
 9   Experience_Level  2000 non-null   object
 10  Attrition_Flag    2000 non-null   int64
 11  Salary_Category   2000 non-null   object
dtypes: int64(5), object(7)
memory usage: 187.6+ KB

In [10]:
df.describe()

,Employee_ID,Age,Monthly_Income,Years_At_Company,Attrition_Flag
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,38.744000,55540.623000,9.539000,0.292500
std,577.494589,11.744805,25572.797337,5.772273,0.455024
min,1.000000,18.000000,10060.000000,0.000000,0.000000
25%,500.750000,29.000000,34360.750000,5.000000,0.000000
50%,1000.500000,39.000000,55371.000000,10.000000,0.000000
75%,1500.250000,49.000000,77292.500000,15.000000,1.000000
max,2000.000000,59.000000,99941.000000,19.000000,1.000000

In [11]:
df.isnull().sum()

Employee_ID          0
Age                  0
Department           0
JobRole              0
Monthly_Income       0
Years_At_Company     0
Gender               0
Attrition            0
Age_Group           46
Experience_Level     0
Attrition_Flag       0
Salary_Category      0
dtype: int64

In [12]:
df= df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.loc[:,"Age"] = df["Age"].fillna(df["Age"].median())

In [15]:
df.loc[:,"Monthly_Income"] = df["Monthly_Income"].fillna(df["Monthly_Income"].median())

In [16]:
df.columns

Index(['Employee_ID', 'Age', 'Department', 'JobRole', 'Monthly_Income',
       'Years_At_Company', 'Gender', 'Attrition', 'Age_Group',
       'Experience_Level', 'Attrition_Flag', 'Salary_Category'],
      dtype='object')

In [17]:
df["Age"].isnull().sum()

np.int64(0)

In [18]:
df.loc[:,'Age'] = df['Age'].astype(int)

In [19]:
df.dtypes

Employee_ID          int64
Age                  int64
Department          object
JobRole             object
Monthly_Income       int64
Years_At_Company     int64
Gender              object
Attrition           object
Age_Group           object
Experience_Level    object
Attrition_Flag       int64
Salary_Category     object
dtype: object

In [20]:
df['Department'].unique()

array(['Finance', 'HR', 'Marketing', 'Sales', 'IT', 'Unknown'],
      dtype=object)

In [21]:
import numpy as np

In [22]:
df.loc[:,'Department'] = df['Department'].replace('NAN', np.nan)

In [23]:
df['Department'].isnull().sum()

np.int64(0)

In [24]:
df.loc[:,'Department'] = df['Department'].fillna('Unknown')

In [25]:
df.loc[:,'Department'] = df['Department'].str.strip().str.capitalize()

In [26]:
df.loc[:,'Department'] = df['Department'].replace({
    'It' : 'IT',
    'Hr' : 'HR'})

In [27]:
import numpy as np

df.loc[:,'Department'] = df['Department'].replace('Nan', np.nan)

In [28]:
df['JobRole'].unique()

array(['Manager', 'Analyst', 'Executive', 'Clerk', 'Engineer'],
      dtype=object)

In [29]:
df.loc[:,'JobRole'] = df['JobRole'].str.strip().str.capitalize()

In [30]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [31]:
df.loc[:,'Gender'] = df['Gender'].str.strip().str.capitalize()

In [32]:
df.loc[:,'Gender'] = df['Gender'].replace({
    'F' : 'Female',
    'M' : 'Male'})

In [33]:
df.head(100)

,Employee_ID,Age,Department,JobRole,Monthly_Income,Years_At_Company,Gender,Attrition,Age_Group,Experience_Level,Attrition_Flag,Salary_Category
0,1,56,Finance,Manager,92214,14,Male,Yes,46-60,Senior,1,High
1,2,46,HR,Analyst,47052,10,Male,No,46-60,Mid,0,Medium
2,3,32,Marketing,Executive,67769,0,Female,No,26-35,New,0,High
3,4,25,Sales,Analyst,56032,17,Female,Yes,18-25,Senior,1,Medium
4,5,38,HR,Clerk,98721,11,Female,No,36-45,Senior,0,High
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,59,Marketing,Analyst,43302,15,Female,No,46-60,Senior,0,Medium
96,97,56,HR,Analyst,95382,1,Male,No,46-60,New,0,High
97,98,58,IT,Clerk,14011,11,Female,No,46-60,Senior,0,Low
98,99,45,Finance,Engineer,29782,5,Male,No,36-45,Junior,0,Low
99,100,39,Unknown,Manager,55371,10,Female,No,36-45,Mid,0,Medium

In [34]:
df['Attrition'].unique()

array(['Yes', 'No'], dtype=object)

In [35]:
df.loc[:,'Age_Group'] = pd.cut(df['Age'],
                               bins = [18,25,35,45,60],
                               labels = ['18-25', '26-35','36-45', '46-60'])

In [36]:
df.loc[:,'Salary_Category'] = pd.cut(df['Monthly_Income'],
                                     bins = [0,30000,60000,100000],
                                     labels= ['Low','Medium','High'])

In [37]:
df['Experience_Level'] = pd.cut(df['Years_At_Company'],
                               bins=[-1,2,5,10,20],
                               labels=['New','Junior','Mid','Senior'])

In [40]:
df.head(100)

,Employee_ID,Age,Department,JobRole,Monthly_Income,Years_At_Company,Gender,Attrition,Age_Group,Experience_Level,Attrition_Flag,Salary_Category
0,1,56,Finance,Manager,92214,14,Male,Yes,46-60,Senior,1,High
1,2,46,HR,Analyst,47052,10,Male,No,46-60,Mid,0,Medium
2,3,32,Marketing,Executive,67769,0,Female,No,26-35,New,0,High
3,4,25,Sales,Analyst,56032,17,Female,Yes,18-25,Senior,1,Medium
4,5,38,HR,Clerk,98721,11,Female,No,36-45,Senior,0,High
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,59,Marketing,Analyst,43302,15,Female,No,46-60,Senior,0,Medium
96,97,56,HR,Analyst,95382,1,Male,No,46-60,New,0,High
97,98,58,IT,Clerk,14011,11,Female,No,46-60,Senior,0,Low
98,99,45,Finance,Engineer,29782,5,Male,No,36-45,Junior,0,Low
99,100,39,Unknown,Manager,55371,10,Female,No,36-45,Mid,0,Medium

In [41]:
df['Age'].isnull().sum()

np.int64(0)

In [42]:
df['Age'].unique()

array([56, 46, 32, 25, 38, 36, 40, 28, 41, 53, 57, 20, 39, 19, 47, 55, 50,
       29, 42, 44, 59, 45, 54, 24, 26, 35, 21, 31, 43, 37, 52, 34, 23, 51,
       27, 33, 58, 18, 22, 30, 49, 48])

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].median()).astype(int)

In [43]:
df.dtypes

Employee_ID            int64
Age                    int64
Department            object
JobRole               object
Monthly_Income         int64
Years_At_Company       int64
Gender                object
Attrition             object
Age_Group             object
Experience_Level    category
Attrition_Flag         int64
Salary_Category       object
dtype: object

In [ ]:
df.loc[:,'Attrition_Flag'] = df['Attrition'].map({'Yes' : 1, 'No' : 0 })

In [ ]:
df['Attrition_Flag'] = df['Attrition_Flag'].astype(int)

In [ ]:
del df['Salary_category']

In [99]:
df['Monthly_Income']  = df['Monthly_Income'].astype(int)

In [45]:
df.to_csv('hr_analytics_messy_dataset.csv', index = False)